"""empty message

Revision ID: f214f7b9053d
Revises: a25d8cb25b42
Create Date: 2022-12-13 12:48:18.727666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f214f7b9053d'
down_revision = 'a25d8cb25b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_column('summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
